apiVersion: v1
kind: Pod
metadata:
  name: kubia-no-gpu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: NotIn
            values:
            - "true"
  containers:
  - image: luksa/kubia
    name: kubia
